### ISSUE TITLE
Duplicate articles?

### ISSUE THREAD

**Issue by bmschmidt** [TU-plogan/KnowledgeProject#2]
There seem to be two copies of the article ENTOMOLOGY with extremely minor differences. Any idea why?

* https://raw.githubusercontent.com/TU-plogan/KnowledgeProject/main/eb07/TXT/e9/kp-eb0709-005901-0069-v1.txt
* https://raw.githubusercontent.com/TU-plogan/KnowledgeProject/main/eb07/TXT/e9/kp-eb0709-005901-6025-v1.txt

**Comment by pml-gh** [comment]
Good catch, Ben. We had to substitute better images for the first 10 pages or so, and in the TEI, I left the old version in by mistake. (The TEI includes links to the original images.)
