### ISSUE TITLE
Merged articles

### ISSUE THREAD

**Issue by bmschmidt** [TU-plogan/KnowledgeProject#3]
Just browsing a list of the longest articles here, it pops out that `VEGA CARPIO, Lope Felix de` is one of the longest articles overall--the reason appears to be that the article on 'VEGETABLE PHYSIOLOGY' occupies most of the body.

`eb07/TXT/v21/kp-eb0721-056602-0604-v1.txt`

**Comment by bmschmidt** [comment]
And noting also that there seems to be at least one case of the converse: I think that `eb07/TXT/p17/kp-eb0717-040701-6378-v1.txt` is a continuation of the previous article, `PHILOLOGY`: it seems some Greek was rendered as uppercase English and triggered a split.

> 
> PETZETAI Σ.
> 
> ΤΟΥΤΟ το μπαλσαμον ωφελεί εις τδ αδύνατον ζομαχι, καί βοr l Deι την χονευσιν δυναμώνει την καgδιαν. συκώνει ολας τας εμ- %άξε/$ της κο ∣ 7jας ωφελεί εις την ζενωσιν καί βηχα παλαιδν. , Iaτgευει τας εσωτεgικας πληγας τx ίηθας, καί τ2 πνεΰμονος ηγουν πλεμόνια, κινεί τα καταμηνια των γυναικών. ’Εις τας εζωτεξικας πληγας πgεπει να βάζεται με το ξανθό πόσον εις παλαιας. Οσον κal ειονεας 9 καθώς είναι η οπαθιαις i και μαχαιgιαις i καί αλλα κοψίματα ιατξευει καθελογης Φιςολα, καί ολας τας βgομεgας πληγας οπχ εφθασαν εις τδ κοκαλον §αυμάσιως, ωφελεί" εις τα, αυτια οπa τgεχουν εμπυον νά ςαζεται δυο η τgεiς κάμπας ηχούν ζαλαγματίας μεζαμπάκι βgεμμενον εις αυτδ, βάνεται εις ταςπλη-γωμενας δοντοκοιλιαις καί γελούν , ατgευθη. καί ακομι δυναμώνει τα οδοντια οπα κινούν ται δε γελούν να πεσουν’ βοηθοί και απδ την πανάκλαν.

**Comment by pml-gh** [comment]
Should be fixed now. There's a few of these in there, and I appreciate knowing where they are. Don't you just love titles like "Vegetable Physiology"?

**Comment by bmschmidt** [comment]
Have to admit I did a double take on vegetable physiology. Especially because I'm toggled to this from looking at lists of majors, and "Vegetable Physiology" sounds *just* off of the name of some major in the IPEDS system...

**Comment by pml-gh** [comment]
Maybe a course on the biology of couch potatoes?
