### ISSUE TITLE
Is the volume attribute correction?

### ISSUE THREAD

**Issue by bmschmidt** [TU-plogan/KnowledgeProject#4]
[John Mark Ockerbloom](https://twitter.com/JMarkOckerbloom) points out that the headers on the 7th edition files say '9th edition', not '7th' edition. Is that right?

> Source: Encyclopaedia Britannica: A Dictionary of Arts, Sciences,
>  and General Literature. Edited by T. S. Baynes. 9th ed. 25 vols.
>  NY: Charles Scribner's Sons, 1878-1889.

**Comment by pml-gh** [comment]
All fixed.
